### ISSUE TITLE
Remove the 'defineSupportCode' method

### ISSUE THREAD

**Issue by RockMinsk** [reportportal/agent-js-cucumber#15]
Rewrite the code to avoid the following issue: 'defineSupportCode is deprecated'

package.json:
```
"agent-js-cucumber": "^0.1.1",
"protractor": "^5.4.2",
"cucumber": "^5.1.0",
"protractor-cucumber-framework": "^6.1.1"
```
Stack trace:
```
(node:14260) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
[01:31:36] E/launcher - Error: TypeError: this.registerHandler is not a function
    at Object.reportPortalHandlers (E:\EPAM\Task_14\TA_Mentoring_2018\node_modules\agent-js-cucumber\modules\cucumber-epam-reportportal-handler.js:38:10)
    at consumer (E:\EPAM\Task_14\TA_Mentoring_2018\Module9_ProtractorCucumberJS\step_definitions\support\handlers.js:9:32)
    at SupportCodeLibraryBuilder.methods.defineSupportCode._util.default.deprecate.fn (E:\EPAM\Task_14\TA_Mentoring_2018\node_modules\cucumber\lib\support_code_library_builder\index.js:3
0:9)
    at deprecated (internal/util.js:47:15)
    at Object.<anonymous> (E:\EPAM\Task_14\TA_Mentoring_2018\Module9_ProtractorCucumberJS\step_definitions\support\handlers.js:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at supportCodePaths.forEach.codePath (E:\EPAM\Task_14\TA_Mentoring_2018\node_modules\cucumber\lib\cli\index.js:142:42)
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (E:\EPAM\Task_14\TA_Mentoring_2018\node_modules\cucumber\lib\cli\index.js:142:22)
```

**Comment by DzmitryHumianiuk** [comment]
@borisosipov Could you help with this issue?

**Comment by BorisOsipov** [comment]
@RockMinsk Use version from git. `"agent-js-cucumber": "^0.1.1"` is ancient and don't support cucumberjs > v3.
e.g. `"agent-js-cucumber": ""https://github.com/reportportal/agent-js-cucumber.git#56b605586"`

@DzmitryHumianiuk you can close this.

**Comment by BorisOsipov** [comment]
@RockMinsk or push @DzmitryHumianiuk everyday setup proper js client publishing process....

**Comment by DzmitryHumianiuk** [comment]
@filland can you plz setup release pipeline for this agent as well?

**Comment by filland** [comment]
@DzmitryHumianiuk  done

**Comment by DzmitryHumianiuk** [comment]
@filland release latest Verision and close this issue

**Comment by filland** [comment]
@DzmitryHumianiuk @RockMinsk @BorisOsipov here is the repo with up-to-date version of the js cucumber agent - https://www.npmjs.com/package/reportportal-agent-cucumber/v/2.0.6
And the right command to download it:
```
npm i reportportal-agent-cucumber
```
