### ISSUE TITLE
report portal launch is failing to finish 

### ISSUE THREAD

**Issue by rutika89** [reportportal/agent-js-cucumber#168]
**Describe the bug**
... Getting below error when the test execution finishes.
/playwright/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:589
        new Error(`Item with tempId "${itemTempId}" not found`),
        ^
Error: Item with tempId "undefined" not found
    at RPClient.finishTestItem (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:589:9)
    at CucumberReportPortalFormatter.finishFeature (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:169:25)
    at /builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:631:14
    at Array.forEach (<anonymous>)
    at CucumberReportPortalFormatter.onTestRunFinishedEvent (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:630:19)
    at CucumberReportPortalFormatter.eventHandler (/builds/future-state/cov/ait/playwright/node_modules/@reportportal/agent-js-cucumber/modules/cucumber-reportportal-formatter.js:82:23)
    at EventEmitter.emit (node:events:531:35)
    at Coordinator.onWorkerProcessClose (/builds/future-state/cov/ait/playwright/node_modules/@cucumber/cucumber/lib/runtime/parallel/coordinator.js:120:35)
    at ChildProcess.<anonymous> (/builds/future-state/cov/ait/playwright/node_modules/@cucumber/cucumber/lib/runtime/parallel/coordinator.js:93:18)
    at ChildProcess.emit (node:events:519:28)

Also, on report portal ui the launch is continually running.

**Expected behavior**
... Should be able to finish launch successfully.

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP : API Service: 5.10.0;Index Service: 5.10.0;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by AmsterGet** [comment]
Hello @rutika89 !
Is it possible to reproduce this problem with the previous minor version of `agent-js-cucumber` (5.3.1)? 
Could you also provide a small example with tests where we can reproduce the issue?
Thanks!

**Comment by sreenidhi27** [comment]
I also faced the same issue with the latest version for  "@reportportal/agent-js-cucumber": "^5.4.0" & is resolved when tried with the older version "@reportportal/agent-js-cucumber": "^5.3.1" @AmsterGet. 

This issue still exists for the latest agent-js-cucumber version. Please do help to check. 

Thanks for tip.

**Comment by rutika89** [comment]
@AmsterGet This indeed works with version `5.3.1`. Facing the same issue however, with latest version as well.

**Comment by TimTim757** [comment]
Configuration:

   "@reportportal/agent-js-cucumber": "5.5.0",
    "@reportportal/client-javascript": "5.3.0",
    
The error with mentioned configuration - @reportportal/client-javascript/lib/report-portal-client.js:592
new Error(`Item with tempId "${itemTempId}" not found`).

The mentioned error disappeared after the  "@reportportal/agent-js-cucumber" downgraded to the version "5.3.1"

**Comment by SonamNapses** [comment]
My error disappeared but the launch is not stopping in reportportal

**Comment by HardKode** [comment]
I am having the same issue. Going to 5.3.1 helped with the error but launches do not finish in report portal . I have to manually force finish

**Comment by LyubomirStoimchev** [comment]
Any updates on when it might be fixed?

**Comment by AmsterGet** [comment]
Hello @lcharlois-neotys !
Thank you very much for your observations and suggested solution.

Checking `tempId` for `undefined` in the `finishFeature` method solves the problem, but this still doesn't remove the stored redundant `feature` objects.
I'm wondering if it's possible to define in `onGherkinDocumentEvent` which `feature`s will be executed, so that only the necessary `feature` data is stored.
In this case, we would not have `undefined` `tempId`s in any method.

Let me know what you think of this solution!

**Comment by prince-inbaraj-sky** [comment]
> Hello [@lcharlois-neotys](https://github.com/lcharlois-neotys) ! Thank you very much for your observations and suggested solution.
> 
> Checking `tempId` for `undefined` in the `finishFeature` method solves the problem, but this still doesn't remove the stored redundant `feature` objects. I'm wondering if it's possible to define in `onGherkinDocumentEvent` which `feature`s will be executed, so that only the necessary `feature` data is stored. In this case, we would not have `undefined` `tempId`s in any method.
> 
> Let me know what you think of this solution!

Hi @AmsterGet,

I'm also facing same issue with "@reportportal/agent-js-cucumber": "^5.5.1" version. 
It will be great if you can provide fix ASAP.

**Comment by maria-hambardzumian** [comment]
Hi @prince-inbaraj-sky @lcharlois-neotys,
We've released patch version 5.5.2, which includes a fix to ensure that only started features are finished. This should resolve the issue, but please let us know if it works for you.

**Comment by prince-inbaraj-sky** [comment]
> Hi [@prince-inbaraj-sky](https://github.com/prince-inbaraj-sky) [@lcharlois-neotys](https://github.com/lcharlois-neotys), We've released patch version 5.5.2, which includes a fix to ensure that only started features are finished. This should resolve the issue, but please let us know if it works for you.

@maria-hambardzumian working fine
Thanks for the update
