### ISSUE TITLE
eventBroadcaster not defined in cucumber-epam-reportportal-handler.js file

### ISSUE THREAD

**Issue by pratyush23** [reportportal/agent-js-cucumber#23]
Just cloned the repo in my machine and configured the rpConfig.json file with my report portal account key. Below are the next basic steps done for running the code:
1. npm install
2. npm run testSingle

It throws an error "**TypeError: Cannot read property 'on' of undefined**"

Node Version (11.10.0). Also tried downgrading the node to versions 10,9 and 8 but same error pops up.
Below is the log:

`npm run testSingle

> reportportal-agent-cucumber@2.0.6 testSingle /Users/sharmp09/workspace/agent-js-cucumber
> cd testSample && npm run testSingle 

> @ testSingle /Users/sharmp09/workspace/agent-js-cucumber/testSample
> ../node_modules/cucumber/bin/cucumber.js ./features/scenarioOutline.feature

TypeError: Cannot read property 'on' of undefined
    at Object.reportPortalHandlers (/Users/sharmp09/workspace/agent-js-cucumber/modules/cucumber-epam-reportportal-handler.js:187:27)
    at consumer (/Users/sharmp09/workspace/agent-js-cucumber/testSample/features/step_definitions/support/handlers.js:8:30)
    at /Users/sharmp09/workspace/agent-js-cucumber/node_modules/cucumber/lib/support_code_library/builder.js:77:12
    at Array.forEach (<anonymous>)
    at Object.build (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/cucumber/lib/support_code_library/builder.js:76:7)
    at Cli.getSupportCodeLibrary (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/cucumber/lib/cli/index.js:137:32)
    at Cli.<anonymous> (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/cucumber/lib/cli/index.js:144:39)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/sharmp09/workspace/agent-js-cucumber/node_modules/bluebird/js/release/async.js:147:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ testSingle: `../node_modules/cucumber/bin/cucumber.js ./features/scenarioOutline.feature`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ testSingle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sharmp09/.npm/_logs/2019-07-23T10_43_00_958Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reportportal-agent-cucumber@2.0.6 testSingle: `cd testSample && npm run testSingle `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reportportal-agent-cucumber@2.0.6 testSingle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sharmp09/.npm/_logs/2019-07-23T10_43_01_007Z-debug.log`

**Comment by sujithshajee** [comment]
was there any luck with resolution on this issue?

**Comment by AmsterGet** [comment]
Cloased as inactual.
