### ISSUE TITLE
Sample Project is not working properly

### ISSUE THREAD

**Issue by mbhandigare** [reportportal/agent-js-cucumber#24]
We tried to use sample project but we got plenty of errors. Is it working?
Also we made changes in our existing project to use this but we faced lots of error

**Comment by davoodharun** [comment]
I can verify this.

Node 11.15
Cucumber 5.0.3

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/harundavood/repo/agent-js-cucumber/node_modules/cucumber/lib/cli/run.js:8:32)

**Comment by AmsterGet** [comment]
Hi guys!
Sorry for the late notification.
Now we have [`@reportportal/agent-js-cucumber`](https://www.npmjs.com/package/@reportportal/agent-js-cucumber) with RP 5.0 full compatibility.
Examples have been moved to a separate repository [examples-js](https://github.com/reportportal/examples-js/tree/master/example-cucumber).
So I will close this question. Feel free reopen it if you have any other questions on the topic.
