### ISSUE TITLE
Feature without description is throwing error

### ISSUE THREAD

**Issue by karthick2007** [reportportal/agent-js-cucumber#25]
I installed reportportal-agent-cucumber package as dependency for my protractor cucumber test workspace.

When i ran the test for a feature file with just name and not specifying description , i am getting below error,
Eg: 
**Feature: name of the feature**

Unhandled rejection ReferenceError: **featureUri is not defined**
    at EventEmitter.eventBroadcaster.on (D:\********\node_modules\reportportal-agent-cucumber\modules\cucumber-epam-reportportal-handler.js:201:87)
    at EventEmitter.emit (events.js:203:15)
    at D:\********\node_modules\cucumber\src\cli\helpers.js:59:26
    at Array.forEach (<anonymous>)
    at D:\********\node_modules\cucumber\src\cli\helpers.js:54:10
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (D:\********\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (D:\********\node_modules\bluebird\js\release\generators.js:97:49)
    at D:\********\node_modules\bluebird\js\release\generators.js:201:15
    at getTestCases (D:\********\node_modules\cucumber\lib\cli\helpers.js:102:18)
    at D:\********\node_modules\cucumber\src\cli\helpers.js:32:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (D:\********\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (D:\********\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (D:\********\node_modules\bluebird\js\release\promise.js:579:26)
    at Promise._settlePromise0 (D:\********\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\********\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\********\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\***********\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\******\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\***********\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)

**Comment by karthick2007** [comment]
I debugged the code and found under **cucumber-epam-reportportal-handler.js**, line 202 , logic to initialize _description_ variable 
**line 202  -  let description = featureDocument.description ? featureDocument.description : featureUri;
line 203  - let featureUri = getUri(event.uri);**

I noticed featureUri is initialized only on line 203 but its value is called on line 202

**Comment by AmsterGet** [comment]
Already fixed in the [https://github.com/reportportal/agent-js-cucumber](master) branch
