### ISSUE TITLE
Sample Project Fails

### ISSUE THREAD

**Issue by contd** [reportportal/agent-js-cucumber#85]
I've tried to setup the sample project to point to our server (changing only the config file) and they all fail.  Here is the modified package.json and errors from STDOUT and .npm/logs/:

```
{
  "scripts": {
    "example:simpleTest": "cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js",
    "example:simpleTestWithRetries": "cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js --retry 2",
    "example:seleniumWebdriverTest": "cucumber-js features/webdriverIntegrationFeature/ --require=features/webdriverIntegrationFeature/**/*.js",
    "example:attachmentTest": "cucumber-js features/attachments/ --require=features/attachments/**/*.js",
    "example:descriptionsTest": "cucumber-js features/descriptions/ --require=features/descriptions/**/*.js",
    "example:logsTest": "cucumber-js features/logs  --require=features/logs/**/*.js",
    "example:testCaseIdTest": "cucumber-js features/testCaseId --require=features/testCaseId/**/*.js",
    "example:attributesTest": "cucumber-js features/attributes --require=features/attributes/**/*.js",
    "example:statusesTest": "cucumber-js features/statuses --require=features/statuses/**/*.js"
  },
  "dependencies": {
    "@reportportal/agent-js-cucumber": "^5.0.2",
    "chromedriver": "^90.0.0",
    "cucumber": "^6.0.5",
    "selenium-webdriver": "^3.5.0"
  },
  "peerDependencies": {
    "cucumber": "4.x - 6.x"
  }
}
```

STDOUT

```
> @ example:simpleTestWithRetries /home/jason/apex/examples-js-master/example-cucumber
> cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js --retry 2

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ example:simpleTestWithRetries: `cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js --retry 2`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ example:simpleTestWithRetries script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jason/.npm/_logs/2021-08-13T19_17_40_786Z-debug.log
```

From the .npm/logs/xxxxx.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/jason/.nvm/versions/node/v10.18.1/bin/node',
1 verbose cli   '/home/jason/.nvm/versions/node/v10.18.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'example:simpleTestWithRetries' ]
2 info using npm@6.13.4
3 info using node@v10.18.1
4 verbose run-script [ 'preexample:simpleTestWithRetries',
4 verbose run-script   'example:simpleTestWithRetries',
4 verbose run-script   'postexample:simpleTestWithRetries' ]
5 info lifecycle @~preexample:simpleTestWithRetries: @
6 info lifecycle @~example:simpleTestWithRetries: @
7 verbose lifecycle @~example:simpleTestWithRetries: unsafe-perm in lifecycle true
8 verbose lifecycle @~example:simpleTestWithRetries: PATH: /home/jason/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jason/apex/examples-js-master/example-cucumber/node_modules/.bin:/home/jason/.poetry/bin:/home/jason/bin:/home/jason/bin:/home/jason/.local/bin:/home/jason/.nvm/versions/node/v10.18.1/bin:/home/jason/perl5/perlbrew/bin:/home/jason/.poetry/bin:/home/jason/.pyenv/plugins/pyenv-virtualenv/shims:/home/jason/.pyenv/shims:~/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/jason/Android/Sdk/tools:/home/jason/Android/Sdk/tools/bin:/home/jason/Android/Sdk/platform-tools:/usr/local/go/bin:/home/jason/go/bin
9 verbose lifecycle @~example:simpleTestWithRetries: CWD: /home/jason/apex/examples-js-master/example-cucumber
10 silly lifecycle @~example:simpleTestWithRetries: Args: [ '-c',
10 silly lifecycle   'cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js --retry 2' ]
11 silly lifecycle @~example:simpleTestWithRetries: Returned: code: 1  signal: null
12 info lifecycle @~example:simpleTestWithRetries: Failed to exec example:simpleTestWithRetries script
13 verbose stack Error: @ example:simpleTestWithRetries: `cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js --retry 2`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jason/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/jason/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd /home/jason/apex/examples-js-master/example-cucumber
16 verbose Linux 5.4.0-80-generic
17 verbose argv "/home/jason/.nvm/versions/node/v10.18.1/bin/node" "/home/jason/.nvm/versions/node/v10.18.1/bin/npm" "run" "example:simpleTestWithRetries"
18 verbose node v10.18.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ example:simpleTestWithRetries: `cucumber-js features/simpleFeature/ --require=features/simpleFeature/**/*.js --retry 2`
22 error Exit status 1
23 error Failed at the @ example:simpleTestWithRetries script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Out ReportPortal server info:

Current version: API Service: 5.4.0; Index Service: 5.0.10; Jobs Service: 5.4.0; Authorization Service: 5.4.0; Service UI: 5.4.0;

**Comment by AmsterGet** [comment]
Hi @contd !
You see an error in the console because some tests have failed. So this is the expected behavior when you run some tests that should definitely fail.
